# Generated by Django 5.0.6 on 2024-05-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fact_data", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="positions",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="hands",
            unique_together={("cards", "suite")},
        ),
    ]
