# Generated by Django 5.0.6 on 2024-06-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fact_data", "0002_alter_positions_name_alter_hands_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Authors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
