# Generated by Django 5.0.6 on 2024-05-26 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fact_data", "0001_initial"),
        ("moves", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="setup",
            name="hand",
        ),
        migrations.AddField(
            model_name="setup",
            name="current_move",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moves",
                to="moves.moveset",
            ),
        ),
        migrations.AddField(
            model_name="setup",
            name="hands",
            field=models.ManyToManyField(related_name="stacks", to="fact_data.hands"),
        ),
        migrations.AlterField(
            model_name="setup",
            name="position",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="setups",
                to="fact_data.positions",
            ),
        ),
        migrations.AlterField(
            model_name="setup",
            name="stack",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="setups",
                to="fact_data.stacks",
            ),
        ),
        migrations.DeleteModel(
            name="Move",
        ),
    ]
