# Generated by Django 5.0.6 on 2024-05-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moves", "0002_remove_setup_hand_setup_current_move_setup_hands_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moveset",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
