# Generated by Django 5.0.6 on 2024-06-04 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fact_data", "0003_authors"),
        ("moves", "0003_alter_moveset_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="setup",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="setups",
                to="fact_data.authors",
            ),
        ),
    ]
